# Generated by Django 3.2.9 on 2022-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('amount', models.FloatField(max_length=20, verbose_name='Количество')),
                ('distance', models.FloatField(max_length=20, verbose_name='Расстояние')),
            ],
        ),
    ]
